### ISSUE TITLE
Coal-mine test found use of merge that doesn't conform to spec

### ISSUE THREAD

**Issue by borkdude** [slipset/speculative#113]
This build runs a random coal-mine test: https://circleci.com/gh/slipset/speculative/339?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Apparently people are using `merge` like:

```
(merge #{1 4 6 3 2 5} 7 1 3 5)
```

What's they reason they did this? Was there a valid reason they didn't use `conj`?
https://github.com/mfikes/coal-mine/blob/606fd7e7c89138f2d69a40521083d2003cd44a1c/src/coal_mine/problem_88.cljc#L218

**Comment by mfikes** [comment]
https://github.com/mfikes/coal-mine/commit/1cdd00c3e5a7412f20258090bbb2290287f74edb

**Comment by borkdude** [comment]
Thanks @mfikes 

Other non-passing solutions:

```
ERROR in (solution-71696517) (alpha.clj:132)
ERROR in (solution-7ca5d8df) (alpha.clj:132)
ERROR in (solution-6d3c9951) (alpha.clj:132)
ERROR in (solution-140aa5fe) (alpha.clj:132)
```

Apparently `(apply merge set1 set2)` is a popular idiom among 4clojurians.

**Comment by borkdude** [comment]
Same thing here: https://github.com/mfikes/coal-mine/pull/89
