### ISSUE TITLE
Collection functions should prefer trait checks over coll types

### ISSUE THREAD

**Issue by puredanger** [slipset/speculative#46]
The collection approach being taken in assoc is bad. In general, the collection functions in Clojure are not based on collection types but on the trait interfaces (here, `associative?`). Narrowing this to just map and vector breaks any custom types in the wild that are Associative (and work just fine with assoc). 

Similar kinds of issues in merge / merge-with I suspect. In general, choose the most generic pred you can.

**Comment by slipset** [comment]
I agree with using the most generic pred. But in the case of `assoc`, the types of the arguments following the `associative?` thing depends on the type of the associative. Would you, and if so, how would you, encode that in spec?

**Comment by puredanger** [comment]
I wouldn't.

**Comment by borkdude** [comment]
@puredanger What about

```
 (merge {:a 1} (java.util.HashMap. {:b 2}))
```

and 

```
(require '[clojure.set :as set])
(set/map-invert (java.util.HashMap. {:b 2}))
```
The latter is reported in #70, @eerohele found it when instrumenting Datomic, `map?` didn't cut it.

We could use `(defn map?* [m] #?(:clj (instance? java.util.Map m) :cljs (map? m)))` in places where `java.util.Map` can be used, but I'd like to hear if this is supposed to be supported.

**Comment by borkdude** [comment]
@puredanger Another one we're debating over in #70:
`data.diff` uses `set.union` in one place where it's called with non-sets. I believe this call should either use `into` user pass `sets`. Should we account for non-set usage of `set.union`?

**Comment by puredanger** [comment]
I think these should be covered by the spec (in other words, I think this is valid code). These coll functions are intentionally polymorphic and support a lot of cases.
