### ISSUE TITLE
reducibles

### ISSUE THREAD

**Issue by puredanger** [slipset/speculative#47]
The spelling we use in core is "reducible", not "reduceable", just fyi. 

The impl here checks IReduce and IReduceInit, but the former derives from the latter, so just checking IReduceInit is sufficient. However, there is also the CollReduce protocol, which covers a lot of additional cases.

**Comment by borkdude** [comment]
ClojureScript already has a predicate called `reduceable?`

**Comment by puredanger** [comment]
bleh
