### ISSUE TITLE
count returns an integer

### ISSUE THREAD

**Issue by puredanger** [slipset/speculative#53]
The `count` spec has :ret number? but count always returns an integer. Exactly which integer pred to use is tricky. Java interfaces use int and due to some of the OO hierarchy, the parts of Clojure in Java do as well. Really, we'd prefer to extend this up to longs though (there is a ticket for this in jira). So I think I would recommend `int?` as the best expression of intent.

**Comment by slipset** [comment]
Thanks a lot for reporting this and bringing clarity. Much appreciated!
